
export const CREATE_ASSIGNMENT = "CREATE_ASSIGNMENT";
export const FETCH_ASSIGNMENTS = "FETCH_ASSIGNMENTS";
export const UPDATE_ASSIGNMENTS = "UPDATE_ASSIGNMENTS";
export const GET_ASSIGNMENT_BY_ID="GET_ASSIGNMENT_BY_ID";
export const DELETE_ASSIGNMENT = "DELETE_ASSIGNMENT"


